Updated actions

diff --git a/.github/workflows/build-0.4.x.x.yml b/.github/workflows/build-0.4.x.x.yml
--- a/.github/workflows/build-0.4.x.x.yml
+++ b/.github/workflows/build-0.4.x.x.yml
@@ -176,25 +176,37 @@ jobs:
   release_checks:
     runs-on: ubuntu-latest
     needs: [ test ]
+    outputs:
+      should_publish: ${{ steps.release_decision.outputs.should_release }}
     steps:
-      - name: Check test status
+      - name: Print current configuration
         run: |
-          echo "Python 3.7: ${{ needs.test.outputs.success_rate_python_3_7 }}"
-          echo "Python 3.8: ${{ needs.test.outputs.success_rate_python_3_8 }}"
-          echo "Python 3.9: ${{ needs.test.outputs.success_rate_python_3_9 }}"
+          echo "Python 3.7: ${{ needs.test.outputs.success_rate_python_3_7 }}%"
+          echo "Python 3.8: ${{ needs.test.outputs.success_rate_python_3_8 }}%"
+          echo "Python 3.9: ${{ needs.test.outputs.success_rate_python_3_9 }}%"
+      - name: Take release decision
+        id: release_decision
+        run: |
+          echo "success_threshold=90"
+          should_release=`echo "${{ needs.test.outputs.success_rate_python_3_7 }} > $success_threshold && ${{ needs.test.outputs.success_rate_python_3_8 }} > $success_threshold && ${{ needs.test.outputs.success_rate_python_3_9 }} > $success_threshold" | bc -l`
+          echo "::set-output name=should_release::$should_release"
+          echo "Release decision: $should_release"
+          if [[ $success_threshold != "1" ]]; then
+            echo "Failing as one of the tests did not reach the minumum pass-threshold."
+            exit 1
 
   # -----------------------------
   # Build and Release
   # -----------------------------
   release:
     runs-on: ubuntu-latest
-    needs: [test, build, release_checks]
-    if: needs.test.outputs.success_rate_python_3_7 > 60 && needs.test.outputs.success_rate_python_3_8 > 60 && needs.test.outputs.success_rate_python_3_9 > 60
+    needs: [release_checks]
+    if: ${{ success() }}
     steps:
-      - name: Setup Python 3.8
+      - name: Setup Python 3.9
         uses: actions/setup-python@v2
         with:
-          python-version: 3.8
+          python-version: 3.9
       - uses: actions/checkout@v2
       - name: Install python dependencies
         run: |
